/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package bz.davide.dmweb.shared.view.example;


public class LeafletMapExampleMarshaller_Helper extends bz.davide.dmweb.shared.i18n.LeafletMapExampleMarshaller_Helper
{
   protected LeafletMapExampleMarshaller_Helper()
   {
      this.putClassMarshaller("bz.davide.dmweb.shared.view.example.LeafletMapExample$InitParameters", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            internalMarschall(obj, "bz.davide.dmweb.shared.view.DivView$InitParameters", "N/A",structure, identities, seq, true);
            Object value;
            // map
            value = ((bz.davide.dmweb.shared.view.example.LeafletMapExample.InitParameters)obj).map;
            if (value == null)
               structure.property("map").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.view.LeafletMapView$InitParameters", structure.property("map").structure(), identities, seq, false);
            }
            // pois
            value = ((bz.davide.dmweb.shared.view.example.LeafletMapExample.InitParameters)obj).pois;
            if (value == null)
               structure.property("pois").nullValue();
            else
            {
               bz.davide.dmweb.shared.view.example.POI[] rawarray = (bz.davide.dmweb.shared.view.example.POI[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("pois").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "bz.davide.dmweb.shared.view.example.POI", array.item().structure(), identities, seq, false);
               }                                                              
            }
            // title
            value = ((bz.davide.dmweb.shared.view.example.LeafletMapExample.InitParameters)obj).title;
            if (value == null)
               structure.property("title").nullValue();
            else
            {
                    structure.property("title").string((String)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("bz.davide.dmweb.shared.view.example.LeafletMapExample", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            internalMarschall(obj, "bz.davide.dmweb.shared.view.DivView", "N/A",structure, identities, seq, true);
            Object value;
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("bz.davide.dmweb.shared.view.example.LeafletMapExampleAttachListener", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // leafletMap
            value = ((bz.davide.dmweb.shared.view.example.LeafletMapExampleAttachListener)obj).leafletMap;
            if (value == null)
               structure.property("leafletMap").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.view.LeafletMapView", structure.property("leafletMap").structure(), identities, seq, false);
            }
            // pois
            value = ((bz.davide.dmweb.shared.view.example.LeafletMapExampleAttachListener)obj).pois;
            if (value == null)
               structure.property("pois").nullValue();
            else
            {
               bz.davide.dmweb.shared.view.example.POI[] rawarray = (bz.davide.dmweb.shared.view.example.POI[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("pois").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "bz.davide.dmweb.shared.view.example.POI", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("bz.davide.dmweb.shared.view.example.POI", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // lat
            value = ((bz.davide.dmweb.shared.view.example.POI)obj).lat;
            if (value == null)
               structure.property("lat").nullValue();
            else
            {
                    structure.property("lat").decimal((Double)value);                          
            }
            // lon
            value = ((bz.davide.dmweb.shared.view.example.POI)obj).lon;
            if (value == null)
               structure.property("lon").nullValue();
            else
            {
                    structure.property("lon").decimal((Double)value);                          
            }
            // name
            value = ((bz.davide.dmweb.shared.view.example.POI)obj).name;
            if (value == null)
               structure.property("name").nullValue();
            else
            {
                    structure.property("name").string((String)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });

   }
}
